# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Mon Feb 26 15:54:36 2024
# ------------------------------------------------

package:
  name: autopep8
  version: 2.0.4
source:
  sha256: 2913064abd97b3419d1cc83ea71f042cb821f87e45b9c88cad5ad3c4ea87fe0c
  url: https://pypi.io/packages/source/a/autopep8/autopep8-2.0.4.tar.gz
build:
  entry_points:
    - autopep8 = autopep8:main
  noarch: python
  number: '0'
  script: /croot/autopep8_1708962882016/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install --no-deps --no-build-isolation . -vv
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2023.12.12 h06a4308_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.4 h6a678d5_0
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.13 h7f8727e_0
    - pip 23.3.1 py311h06a4308_0
    - python 3.11.7 h955ad1f_0
    - readline 8.2 h5eee18b_0
    - setuptools 68.2.2 py311h06a4308_0
    - sqlite 3.41.2 h5eee18b_0
    - tk 8.6.12 h1ccaba5_0
    - tzdata 2024a h04d1e81_0
    - wheel 0.41.2 py311h06a4308_0
    - xz 5.4.5 h5eee18b_0
    - zlib 1.2.13 h5eee18b_0
  run:
    - pycodestyle >=2.10.0
    - python >=3.6
test:
  commands:
    - pip check
    - autopep8 --help
  imports:
    - autopep8
  requires:
    - pip
about:
  dev_url: https://github.com/hhatto/autopep8
  doc_url: https://github.com/hhatto/autopep8/blob/master/README.rst
  home: https://github.com/hhatto/autopep8
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A tool that automatically formats Python code to conform to the PEP 8 style
    guide
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 4f69c24c-426b-420b-b970-d7bc19a67dd5
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
  remote_url: git@github.com:AnacondaRecipes/autopep8-feedstock.git
  sha: 6955f3f7b9899877f0a716a160c90bc4354a3a4c
