# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Thu Sep 12 14:11:38 2024
# ------------------------------------------------

package:
  name: pycodestyle
  version: 2.12.1
source:
  fn: pycodestyle-2.12.1.tar.gz
  sha256: 6838eae08bbce4f6accd5d5572075c63626a15ee3e6f842df996bf62f6d73521
  url: https://pypi.io/packages/source/p/pycodestyle/pycodestyle-2.12.1.tar.gz
build:
  entry_points:
    - pycodestyle = pycodestyle:_main
  number: '0'
  script: /croot/pycodestyle_1726150303809/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps -vv --no-build-isolation
  string: py310h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2024.7.2 h06a4308_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.15 h5eee18b_0
    - pip 24.2 py310h06a4308_0
    - python 3.10.14 h955ad1f_1
    - readline 8.2 h5eee18b_0
    - setuptools 72.1.0 py310h06a4308_0
    - sqlite 3.45.3 h5eee18b_0
    - tk 8.6.14 h39e8969_0
    - tzdata 2024a h04d1e81_0
    - wheel 0.43.0 py310h06a4308_0
    - xz 5.4.6 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - python >=3.10,<3.11.0a0
test:
  commands:
    - pip check
    - pycodestyle --help
    - pycodestyle --version
  imports:
    - pycodestyle
  requires:
    - pip
about:
  description: 'Pycodestyle is a tool to check your Python code against some of the
    style conventions in PEP 8.

    '
  dev_url: https://github.com/PyCQA/pycodestyle
  doc_url: https://pycodestyle.pycqa.org
  home: https://pycodestyle.pycqa.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python style guide checker
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 82cb3e8a-7ba6-46b4-9621-7f4de1149b90
  recipe-maintainers:
    - dopplershift
    - jakirkham
    - jjhelmus
    - ocefpaf
    - pmlandwehr
    - sigmavirus24
  remote_url: git@github.com:AnacondaRecipes/pycodestyle-feedstock.git
  sha: 657f80131c44230bd6347442079c9e1d43a46939
